# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Extension

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Build static files
      run: npm run build --if-present
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: './dist'
        path: '.'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: 'Extension'
        artifacts: './dist/release.zip'
        allowUpdates: true
        replacesArtifacts: true
        body: |
          ${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
