# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Extension

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:

  chrome:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Rename manifest
      run: mv public/manifest-chrome.json public/manifest.json
    - name: Delete other manifest
      run: rm -f public/manifest-firefox.json
    - name: Build static files
      run: pnpm build
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'chrome.zip'
        directory: './dist'
        path: '.'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: 'Extension'
        artifacts: './dist/chrome.zip'
        allowUpdates: true
        replacesArtifacts: true
        body: |
          ${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}

  firefox:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"
    - name: Install dependencies
      run: pnpm i --frozen-lockfile
    - name: Rename manifest
      run: mv public/manifest-firefox.json public/manifest.json
    - name: Delete other manifest
      run: rm -f public/manifest-chrome.json
    - name: Build static files
      run: pnpm build
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'firefox.zip'
        directory: './dist'
        path: '.'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: 'Extension'
        artifacts: './dist/firefox.zip'
        allowUpdates: true
        replacesArtifacts: true
        body: |
          ${{ github.event.head_commit.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
